# Generated by Django 5.2.7 on 2025-10-05 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FIX', 'Фикс'), ('VAR', 'Переменный'), ('LAB', 'Работа'), ('MAT', 'Материал')], max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
                'indexes': [models.Index(fields=['title'], name='categories_title_e17cea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('messenger', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customers',
                'indexes': [models.Index(fields=['name'], name='customers_name_25d5e3_idx'), models.Index(fields=['phone'], name='customers_phone_91048b_idx'), models.Index(fields=['email'], name='customers_email_92e882_idx'), models.Index(fields=['messenger'], name='customers_messeng_a53b8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.category')),
                ('jobs', models.ManyToManyField(blank=True, related_name='products', to='workshop.job')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('STATUS', 'Статус'), ('CALLBACK', 'Дозвонись'), ('CLIENT', 'Клиент'), ('ASSIGN_MASTER', 'Оформить мастера'), ('ROP_ANALYSIS', 'РОП анализ'), ('NON_TARGET_ROP', 'Нецелевой РОП'), ('ROP_REFUSAL', 'Отказ РОП'), ('PICKUP', 'Забрать забор'), ('CLOSE_OR_FOLLOWUP', 'Дожми или доведи'), ('LOGISTICS_REFUSAL', 'Отказ логистики')], max_length=17)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.job')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.lead')),
            ],
            options={
                'db_table': 'parts',
                'unique_together': {('lead', 'job')},
            },
        ),
    ]
